//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tInventar_nomerov
    {
        public int ID_Nomer { get; set; }
        public string Naimenovanie { get; set; }
        public int ID_inventarnoy_edinitsy { get; set; }
        public int Kolvo_v_nomere { get; set; }
    
        public virtual tNomer tNomer { get; set; }
    }
}
