//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRaskhod_resursov
    {
        public int ID_Resursa { get; set; }
        public int Kolvo_ispolzovannykh { get; set; }
        public Nullable<int> ID_Rabotnika { get; set; }
    
        public virtual tResursy tResursy { get; set; }
        public virtual tSotrudnik tSotrudnik { get; set; }
    }
}
