//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSotrudnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSotrudnik()
        {
            this.tBron_nomera = new HashSet<tBron_nomera>();
            this.tRaskhod_resursov = new HashSet<tRaskhod_resursov>();
        }
    
        public string Imya { get; set; }
        public string Familiya { get; set; }
        public int Vysluga { get; set; }
        public Nullable<int> ID_Dolzhnost { get; set; }
        public int ID_Rabotnika { get; set; }
        public int Vozrast { get; set; }
    
        public virtual tDolzhnost tDolzhnost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBron_nomera> tBron_nomera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRaskhod_resursov> tRaskhod_resursov { get; set; }
    }
}
